site_name: Rachitt Shah
site_author: Rachitt Shah
site_description: >-
  AI Engineering, RAG Systems, and Technical Notes
repo_name: rachittshah.github.io
repo_url: https://github.com/rachittshah/rachittshah.github.io
site_url: https://rachittshah.github.io
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Rachitt Shah

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: rachittshah
      repo: blog
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: 
    - Introduction: 'index.md'
    - About: 'about.md'
  - Blog:
    - All Posts: 'blog/index.md'
    - Tags: 'blog/tags.md'
  - RAG Systems:
    - Introduction: 'rag/index.md'
    - Best Practices: 'rag/best-practices.md'
    - Case Studies: 'rag/case-studies.md'
  - AI Engineering:
    - Overview: 'ai/index.md'
    - Vector Databases: 'ai/vector-databases.md'
    - LLM Integration: 'ai/llm-integration.md'
  - Projects: 'projects.md'
  - Contact: 'contact.md'

plugins:
  - social
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        meta: date
        format: "%Y-%m-%d"
      categories:
        - tags
      comments_path: "#__comments"
      use_git: false
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
      pagination: true
      pagination_per_page: 10
      pagination_format: "Page $page of $total_pages"
      draft_on_serve: true
      draft_if_future_date: true

extra:
  analytics:
    provider: google
    property: # Add your Google Analytics ID
  social:
    - icon: fontawesome/solid/rss
      link: feed_rss_created.xml
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rachittshah
    - icon: fontawesome/brands/github
      link: https://github.com/rachittshah
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rachittshah

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 